apiVersion: v1
kind: ConfigMap
metadata:
  name: supply-volume
data:
  app-config.yaml: |
    graphqlsvc:
      host: http://graphql-server
      port: 8080
    postgresql:
      ssd:
        connectString: host=oes-db user=postgres  password=networks123  database=ssddb
    toolchain:
      host: http://tool-chain
      port: 8100   
