apiVersion: v1
kind: ConfigMap
metadata:
  name: supplychain-preprocessor-cm
data:
  globalConfig.yml: |
    plugins:
      - jenkins
      - spinnaker
    loglevel: info

  jenkinsConfig.yml: |
    rabbitmq:
      username: rabbitmq
      password: Networks123
      host: rabbitmq-service
      port: 5672
      queue: jenkins-ssd
      exchange: jenkins.events
      bindingKey: jenkins-ssd

    postgresql:
      ssddb:
        connectString: host=oes-db user='postgres' password='networks123' database=ssddb port=5432

  spinnakerConfig.yml: |
    rabbitmq:
      username: rabbitmq
      password: Networks123
      host: rabbitmq-service
      port: 5672
      queue: preview-saas-ssd
      exchange: echo.events
      bindingKey: preview-saas-ssd

    postgresql:
      ssddb:
        connectString: host=oes-db user='postgres' password='networks123' database=ssddb port=5432

    guacsvc:
      host: http://tool-chain
      port: 8100  

    policysvc:
      host: http://ssd-opa
      port: 8200
