apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: sapor
    heritage: "Helm"
    release: "isdargo"
    chart: "isdargo-4.1.1"
  name: oes-sapor
spec:
  type: NodePort
  ports:
  - name: "sapor"
    port: 8085
    targetPort: 8085
  selector:
    app: oes
    component: sapor
