apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: ui
    heritage: "Helm"
    release: "isdargo"
    chart: "isdargo-4.1.1"
  name: oes-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: ui
  template:
    metadata:
      annotations:
        checksum/configmap: d884b8c12ed407b0e2ccff621c2ec92c193bdbaf13673ef473491437cae9a962
      labels:
        app: oes
        component: ui
        heritage: "Helm"
        release: "isdargo"
        chart: "isdargo-4.1.1"
    spec:
      containers:
      - image: quay.io/opsmxpublic/ubi8-oes-ui:202308281629-ssd
        name: oes-ui
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: config-dir
          mountPath: /var/www/html/ui/assets/config/app-config.json
          subPath: app-config.json
        - name: config-dir
          mountPath: /var/www/html/ui/assets/config/help-text.json
          subPath: help-text.json
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /ui/indexl.html
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          name: oes-ui-config
        name: config-dir
      - configMap:
          defaultMode: 420
          name: oes-ui-nginxconf
        name: nginx-config
